[phases.build]
commands = [
    "mvn -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install"
]

[phases.start]
commands = [
    "java --module-path /usr/lib/jvm/java-11-openjdk-amd64/lib --add-modules javafx.controls,javafx.fxml -jar target/Proyecto-1.0-SNAPSHOT.jar"
]
